version: "3"

services:
  app:
    image: amazoncorretto:17
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew bootRun
  db:
    image: postgres:15-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root